{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "microservice",
    "label": "microservice",
    "query": {
     "query": "label_values(jvm_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$microservice\"} * 1000"
    }
   ]
  },
  {
   "title": "Documents in db",
   "type": "piechart",
   "description": "how many documants ther eare in db",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "documents_in_db{instance=\"$microservice\"}",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "requests",
   "type": "piechart",
   "description": "get request distrebution",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"$microservice\", status=\"200\"}",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "piechart",
   "description": "how many failed get request happend",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"$microservice\", status!=\"200\"}",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Fail precentage",
   "type": "gauge",
   "description": "% of successes",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(http_server_requests_seconds_count{instance=\"$microservice\", status!=\"200\"}) * 100) / sum(http_server_requests_seconds_count{instance=\"$microservice\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Duration", "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$microservice\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "sum(documents_in_db{instance=\"$microservice\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_sum{instance=\"$microservice\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{instance=\"$microservice\", status!=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "description": "how maby request we get per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"$microservice\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "fail % per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"$microservice\", status!=\"200\"}[1m]))*100 / sum(rate(http_server_requests_seconds_count{status=\"200\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}